# Generated by Django 3.2.3 on 2021-08-02 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('request_method', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('device', models.CharField(max_length=100, null=True)),
                ('browser_family', models.CharField(max_length=100, null=True)),
                ('browser_version', models.CharField(max_length=100, null=True)),
                ('os_family', models.CharField(max_length=100, null=True)),
                ('os_version', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_extra_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=800, null=True)),
                ('center', models.CharField(blank=True, max_length=800, null=True)),
                ('position', models.CharField(blank=True, max_length=800, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('email_signup_confirmed', models.BooleanField(default=False)),
                ('ldap_is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
