# Generated by Django 3.2.3 on 2021-06-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('request_method', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('device', models.CharField(max_length=100, null=True)),
                ('browser_family', models.CharField(max_length=100, null=True)),
                ('browser_version', models.CharField(max_length=100, null=True)),
                ('os_family', models.CharField(max_length=100, null=True)),
                ('os_version', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
