# Generated by Django 3.2.3 on 2021-07-06 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_user_extra_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_extra_details',
            name='ldap_groups',
        ),
        migrations.AddField(
            model_name='user_extra_details',
            name='ldap_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_extra_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
