# Generated by Django 3.2.3 on 2021-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210706_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extra_details',
            name='email_signup_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
