# Generated by Django 3.2.3 on 2021-08-02 04:40

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='container_display_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='html_lang_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meta_author_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meta_charset_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_settings_locale_includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_text', models.CharField(max_length=100)),
                ('name_order_by', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(230)])),
                ('is_actual', models.BooleanField(default=True)),
                ('href', models.CharField(blank=True, default='#', max_length=800, null=True)),
            ],
            options={
                'ordering': ('name_order_by',),
                'unique_together': {('name', 'name_order_by')},
            },
        ),
        migrations.CreateModel(
            name='aside_left_menu_includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menu_level', models.CharField(choices=[('level-menu', 'level-menu'), ('level-0', 'level-0'), ('level-1', 'level-1'), ('level-2', 'level-2'), ('level-3', 'level-3'), ('level-4', 'level-4'), ('level-5', 'level-5')], default='level-0', max_length=15)),
                ('menu_icon_type', models.CharField(choices=[('folder', 'folder'), ('arrow', 'arrow')], default='arrow', max_length=15)),
                ('name_order_by', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=1)),
                ('parent_name_order_by', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=1)),
                ('render_app_name', models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], default='zs_admin', max_length=70, null=True)),
                ('source_app_name', models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], default='os_dashboards', max_length=70, null=True)),
                ('href', models.CharField(blank=True, default='#', max_length=800, null=True)),
                ('external_href', models.TextField(blank=True, default='#', null=True)),
                ('source_type', models.CharField(choices=[('external', 'external'), ('internal', 'internal')], default='external', max_length=20)),
                ('level_menu_svg_icon', models.TextField(blank=True, null=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('parent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_parent_name', to='app_zs_admin.aside_left_menu_includes')),
                ('source_app_name_translate', models.ForeignKey(blank=True, limit_choices_to={'menu_level': 'level-menu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_render_app_name_translate', to='app_zs_admin.aside_left_menu_includes')),
                ('url_access_via_groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('url_access_via_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('parent_name_order_by', 'name_order_by'),
                'unique_together': {('name', 'parent_name', 'name_order_by', 'parent_name_order_by')},
            },
        ),
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_brand_name', models.CharField(default='DjangoAnalytics', max_length=400)),
                ('app_brand_color', colorfield.fields.ColorField(default='#333', max_length=18)),
                ('app_brand_ico', models.ImageField(null=True, upload_to='img')),
                ('app_brand_logo', models.ImageField(null=True, upload_to='img')),
                ('app_brand_logo_zoom', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('app_breadcrumb_active', models.CharField(blank=True, default='', max_length=400)),
                ('app_settings_header_section_left_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_left_button_menu_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_left_brand_details_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_center_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_search_extra_button_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_notification_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_locale_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_menu_enable', models.BooleanField(default=True)),
                ('app_settings_container_aside_left_enable', models.BooleanField(default=True)),
                ('app_settings_container_aside_left_main_site_page', models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('accounts', 'accounts'), ('os_dashboards', 'os_dashboards'), ('os_surveys', 'os_surveys'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples'), ('db_sadko', 'db_sadko'), ('db_sqlite_test', 'db_sqlite_test')], max_length=70, null=True)),
                ('app_start_page', models.CharField(choices=[('zs_admin', 'zs_admin'), ('accounts', 'accounts'), ('os_dashboards', 'os_dashboards'), ('os_surveys', 'os_surveys'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples'), ('db_sadko', 'db_sadko'), ('db_sqlite_test', 'db_sqlite_test')], default='zs_admin', max_length=70, null=True)),
                ('app_settings_container_main_bg_color_enable', models.BooleanField(default=True)),
                ('app_settings_container_main_bg_color', colorfield.fields.ColorField(default='#f9f9f9', max_length=18)),
                ('app_settings', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('is_actual', models.BooleanField(default=False)),
                ('app_settings_container_aside_left_menu_items_includes', models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, related_name='aside_left_menu', to='app_zs_admin.aside_left_menu_includes')),
                ('app_settings_container_display_mode', models.ManyToManyField(to='app_zs_admin.container_display_mode')),
                ('app_settings_header_section_right_user_settings_locale_includes', models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, to='app_zs_admin.user_settings_locale_includes')),
                ('app_settings_html_lang_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.html_lang_code')),
                ('app_settings_meta_author_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.meta_author_description')),
                ('app_settings_meta_charset_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.meta_charset_code')),
            ],
            options={
                'unique_together': {('app_brand_name', 'app_brand_ico', 'app_brand_logo', 'app_breadcrumb_active')},
            },
        ),
    ]
