# Generated by Django 3.2.3 on 2021-06-27 18:31

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container_display_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='html_lang_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meta_author_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meta_charset_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='settings_menu_includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menu_level', models.CharField(choices=[('level-0', 'level-0'), ('level-1', 'level-1'), ('level-2', 'level-2'), ('level-3', 'level-3'), ('level-4', 'level-4'), ('level-5', 'level-5')], default='level-0', max_length=15)),
                ('menu_icon_type', models.CharField(choices=[('folder', 'folder'), ('arrow', 'arrow')], default='arrow', max_length=15)),
                ('href', models.CharField(blank=True, default='#', max_length=800, null=True)),
                ('order_by', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_settings_locale_includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_text', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, default='#', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_brand_name', models.CharField(default='DjangoAnalytics', max_length=400)),
                ('app_brand_color', colorfield.fields.ColorField(default='#333', max_length=18)),
                ('app_brand_ico', models.ImageField(null=True, upload_to='img')),
                ('app_brand_logo', models.ImageField(null=True, upload_to='img')),
                ('app_brand_logo_zoom', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('app_breadcrumb_active', models.CharField(blank=True, default='', max_length=400)),
                ('app_settings_header_section_left_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_left_button_menu_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_left_brand_details_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_center_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_search_extra_button_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_notification_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_locale_enable', models.BooleanField(default=True)),
                ('app_settings_header_section_right_user_settings_menu_enable', models.BooleanField(default=True)),
                ('app_settings_container_aside_left_enable', models.BooleanField(default=True)),
                ('app_settings_container_aside_left_settings_menu_enable', models.BooleanField(default=True)),
                ('app_settings_container_aside_left_dashboards_menu_enable', models.BooleanField(default=True)),
                ('app_settings', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('is_actual', models.BooleanField(default=False)),
                ('app_settings_container_aside_left_settings_menu_items_includes', models.ManyToManyField(blank=True, to='app_zs_admin.settings_menu_includes')),
                ('app_settings_container_display_mode', models.ManyToManyField(to='app_zs_admin.container_display_mode')),
                ('app_settings_header_section_right_user_settings_locale_includes', models.ManyToManyField(blank=True, to='app_zs_admin.user_settings_locale_includes')),
                ('app_settings_html_lang_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.html_lang_code')),
                ('app_settings_meta_author_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.meta_author_description')),
                ('app_settings_meta_charset_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.meta_charset_code')),
            ],
            options={
                'unique_together': {('app_brand_name', 'app_brand_ico', 'app_brand_logo', 'app_breadcrumb_active')},
            },
        ),
    ]
