# Generated by Django 3.2.6 on 2021-08-23 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_zs_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_content', models.CharField(max_length=100)),
                ('is_actual', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='user_notification_event_confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_user_notification_event_confirm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-confirm_date', 'user'),
            },
        ),
    ]
