# Generated by Django 3.2.3 on 2021-06-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0002_settings_menu_includes_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_menu_includes',
            name='order_by',
        ),
        migrations.AddField(
            model_name='settings_menu_includes',
            name='name_order_by',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AddField(
            model_name='settings_menu_includes',
            name='parent_name_order_by',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
