# Generated by Django 3.2.3 on 2021-06-24 17:54

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0002_rename_app_zs_admin_test_table_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_brand_color',
            field=colorfield.fields.ColorField(default='#333', max_length=18),
        ),
        migrations.AddField(
            model_name='app',
            name='app_brand_ico',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_brand_logo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_brand_logo_zoom',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AddField(
            model_name='app',
            name='app_brand_name',
            field=models.CharField(default='DjangoAnalytics', max_length=400),
        ),
        migrations.AddField(
            model_name='app',
            name='app_breadcrumb_active',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='app',
            name='app_settings',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='is_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('app_brand_name', 'app_brand_ico', 'app_brand_logo', 'app_breadcrumb_active')},
        ),
        migrations.RemoveField(
            model_name='app',
            name='test_field',
        ),
    ]
