# Generated by Django 3.2.6 on 2021-08-26 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_zs_admin', '0003_notification_events_users_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='users_list',
            field=models.ManyToManyField(blank=True, related_name='for_user_notification_event_show', to=settings.AUTH_USER_MODEL),
        ),
    ]
