# Generated by Django 3.2.3 on 2021-06-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0003_auto_20210628_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings_menu_includes',
            options={'ordering': ('name_order_by', 'parent_name_order_by')},
        ),
    ]
