# Generated by Django 3.2.6 on 2021-09-12 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0004_alter_notification_events_users_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_events',
            name='event_content2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
