# Generated by Django 3.2.6 on 2021-09-14 19:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0006_auto_20210914_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='event_content2',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
