# Generated by Django 3.2.3 on 2021-06-27 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0008_alter_settings_menu_includes_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_settings_locale_includes',
            options={'ordering': ('name_order_by',)},
        ),
        migrations.AddField(
            model_name='user_settings_locale_includes',
            name='name_order_by',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(230)]),
        ),
    ]
