# Generated by Django 3.2.3 on 2021-06-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0009_auto_20210628_0206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_settings_locale_includes',
            unique_together={('name', 'name_order_by')},
        ),
    ]
