# Generated by Django 3.2.6 on 2021-09-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0009_alter_notification_events_event_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='event_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
