# Generated by Django 3.2.3 on 2021-06-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0010_alter_user_settings_locale_includes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_menu_includes',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_settings_locale_includes',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
