# Generated by Django 3.2.3 on 2021-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0011_auto_20210628_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_settings_container_aside_left_settings_menu_items_includes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, to='app_zs_admin.settings_menu_includes'),
        ),
    ]
