# Generated by Django 3.2.3 on 2021-06-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0012_alter_app_app_settings_container_aside_left_settings_menu_items_includes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_settings_header_section_right_user_settings_locale_includes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, to='app_zs_admin.user_settings_locale_includes'),
        ),
    ]
