# Generated by Django 3.2.6 on 2021-11-24 20:43

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0012_alter_app_app_settings_container_display_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_message_headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=400)),
                ('codename', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_row', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('message_type', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=40)),
                ('user_messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_zs_admin.user_message_headers')),
            ],
        ),
    ]
