# Generated by Django 3.2.3 on 2021-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0013_alter_app_app_settings_header_section_right_user_settings_locale_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_settings_container_aside_left_dashboards_menu_items_includes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, related_name='dashboards_menu', to='app_zs_admin.settings_menu_includes'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_settings_container_aside_left_settings_menu_items_includes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, related_name='settings_menu', to='app_zs_admin.settings_menu_includes'),
        ),
    ]
