# Generated by Django 3.2.3 on 2021-06-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0014_auto_20210628_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings_menu_includes',
            new_name='aside_left_menu_includes',
        ),
    ]
