# Generated by Django 3.2.3 on 2021-06-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_zs_admin', '0015_rename_settings_menu_includes_aside_left_menu_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='url_groups_permissions',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
