# Generated by Django 3.2.3 on 2021-06-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_zs_admin', '0016_aside_left_menu_includes_url_groups_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aside_left_menu_includes',
            new_name='app_aside_left_menu_includes',
        ),
        migrations.RenameModel(
            old_name='meta_charset_code',
            new_name='app_container_display_mode',
        ),
        migrations.RenameModel(
            old_name='container_display_mode',
            new_name='app_html_lang_code',
        ),
        migrations.RenameModel(
            old_name='meta_author_description',
            new_name='app_meta_author_description',
        ),
        migrations.RenameModel(
            old_name='html_lang_code',
            new_name='app_meta_charset_code',
        ),
        migrations.RenameModel(
            old_name='user_settings_locale_includes',
            new_name='app_user_settings_locale_includes',
        ),
    ]
