# Generated by Django 3.2.3 on 2021-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_zs_admin', '0018_auto_20210629_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='url_groups_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
