# Generated by Django 3.2.3 on 2021-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_zs_admin', '0020_alter_aside_left_menu_includes_url_groups_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aside_left_menu_includes',
            old_name='url_groups_permissions',
            new_name='url_access_via_users',
        ),
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='url_access_via_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
