# Generated by Django 3.2.3 on 2021-06-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0024_alter_aside_left_menu_includes_render_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='render_app_name',
            field=models.CharField(choices=[('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], max_length=15, null=True),
        ),
    ]
