# Generated by Django 3.2.3 on 2021-07-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0029_alter_aside_left_menu_includes_render_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_settings_container_aside_left_main_site_page',
            field=models.CharField(blank=True, choices=[('os_dashboards', 'os_dashboards'), ('op_surveys', 'op_surveys'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples'), ('database_oracle_sadko', 'database_oracle_sadko'), ('database_sqlite_test', 'database_sqlite_test')], max_length=70, null=True),
        ),
    ]
