# Generated by Django 3.2.3 on 2021-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0030_alter_app_app_settings_container_aside_left_main_site_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_settings_container_aside_left_main_site_page',
            field=models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('accounts', 'accounts'), ('os_dashboards', 'os_dashboards'), ('os_surveys', 'os_surveys'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples'), ('db_sadko', 'db_sadko'), ('db_sqlite_test', 'db_sqlite_test')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='render_app_name',
            field=models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], max_length=70, null=True),
        ),
    ]
