# Generated by Django 3.2.3 on 2021-07-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0032_app_app_start_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_start_page',
            new_name='app_zs_admin_start_page',
        ),
    ]
