# Generated by Django 3.2.3 on 2021-07-08 17:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0037_alter_app_app_zs_admin_start_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_zs_admin_start_page',
            new_name='app_start_page',
        ),
        migrations.AddField(
            model_name='app',
            name='app_settings_container_main_bg_color',
            field=colorfield.fields.ColorField(default='#f9f9f9', max_length=18),
        ),
        migrations.AddField(
            model_name='app',
            name='app_settings_container_main_bg_color_enable',
            field=models.BooleanField(default=True),
        ),
    ]
