# Generated by Django 3.2.3 on 2021-07-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0040_auto_20210711_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aside_left_menu_includes',
            unique_together={('name', 'name_order_by', 'parent_name_order_by')},
        ),
        migrations.RemoveField(
            model_name='aside_left_menu_includes',
            name='parent_name2',
        ),
    ]
