# Generated by Django 3.2.3 on 2021-07-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0041_auto_20210711_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_zs_admin.aside_left_menu_includes'),
        ),
        migrations.AlterUniqueTogether(
            name='aside_left_menu_includes',
            unique_together={('name', 'parent_name', 'name_order_by', 'parent_name_order_by')},
        ),
    ]
