# Generated by Django 3.2.3 on 2021-07-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0043_auto_20210720_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='is_new_parent_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='level_menu_svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='render_app_name_translate',
            field=models.ForeignKey(blank=True, limit_choices_to={'menu_level': 'level-menu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_render_app_name_translate', to='app_zs_admin.aside_left_menu_includes'),
        ),
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='menu_level',
            field=models.CharField(choices=[('level-menu', 'level-menu'), ('level-0', 'level-0'), ('level-1', 'level-1'), ('level-2', 'level-2'), ('level-3', 'level-3'), ('level-4', 'level-4'), ('level-5', 'level-5')], default='level-0', max_length=15),
        ),
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_parent_name', to='app_zs_admin.aside_left_menu_includes'),
        ),
    ]
