# Generated by Django 3.2.3 on 2021-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0044_auto_20210723_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_settings_container_aside_left_menu_items_includes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_actual': True}, related_name='aside_left_menu', to='app_zs_admin.aside_left_menu_includes'),
        ),
    ]
