# Generated by Django 3.2.3 on 2021-07-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0045_app_app_settings_container_aside_left_menu_items_includes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='app_settings_container_aside_left_dashboards_menu_enable',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_settings_container_aside_left_dashboards_menu_items_includes',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_settings_container_aside_left_settings_menu_enable',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_settings_container_aside_left_settings_menu_items_includes',
        ),
    ]
