# Generated by Django 3.2.3 on 2021-07-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0046_auto_20210724_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aside_left_menu_includes',
            name='is_new_parent_menu',
        ),
    ]
