# Generated by Django 3.2.3 on 2021-07-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0047_remove_aside_left_menu_includes_is_new_parent_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aside_left_menu_includes',
            old_name='content_href',
            new_name='external_href',
        ),
        migrations.RenameField(
            model_name='aside_left_menu_includes',
            old_name='render_app_name_translate',
            new_name='source_app_name_translate',
        ),
        migrations.AddField(
            model_name='aside_left_menu_includes',
            name='source_app_name',
            field=models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], default='os_dashboards', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='render_app_name',
            field=models.CharField(blank=True, choices=[('zs_admin', 'zs_admin'), ('os_dashboards', 'os_dashboards'), ('zs_dashboards', 'zs_dashboards'), ('zs_examples', 'zs_examples')], default='zs_admin', max_length=70, null=True),
        ),
    ]
