# Generated by Django 3.2.3 on 2021-07-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_admin', '0048_auto_20210726_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside_left_menu_includes',
            name='external_href',
            field=models.TextField(blank=True, default='javascript:document.write(\'<h1 style="width: 100%;height: 100%;display: flex;justify-content: center;align-items: center;padding: 0;margin: 0;">Empty frame content.</h1>\')', null=True),
        ),
    ]
