# Generated by Django 3.2.3 on 2021-08-02 04:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='databaseConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('config', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='processing_module_pipeline_user_content_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('userobject', models.CharField(blank=True, max_length=750, null=True)),
                ('userobjectparams', models.CharField(blank=True, max_length=1500, null=True)),
                ('userobjectwindow', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'processing_module_pipeline_user_content_history',
            },
        ),
        migrations.CreateModel(
            name='test_table_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(max_length=150)),
                ('datetime_start_field', models.DateTimeField(blank=True, null=True)),
                ('datetime_end_field', models.DateTimeField(blank=True, null=True)),
                ('boolean_field', models.BooleanField(default=True)),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('integer_choice_field', models.IntegerField(choices=[(1, 'Value One'), (2, 'Value Two'), (3, 'Value Three'), (4, 'Value Four')], default=0)),
            ],
        ),
    ]
