# Generated by Django 3.2.3 on 2021-06-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zs_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app_zs_dashboards_test_table',
            new_name='app',
        ),
    ]
